name: Build Eleventy

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, edited, reopened ]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build-gh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: needs.pr-check.outputs.number != 'null'
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}
